apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: maturidade-digital
data:
  # Configurações da aplicação
  VITE_APP_NAME: "Maturidade Digital"
  VITE_APP_VERSION: "1.0.0"
  
  # URLs da API
  VITE_API_URL: "https://api.maturidade.sebraemg.com.br/api"
  VITE_DIRECTUS_URL: "https://directus.maturidade.sebraemg.com.br"
  
  # Configurações do Keycloak
  VITE_KEYCLOAK_AUTH_SERVER_URL: "https://amei.sebrae.com.br/auth"
  VITE_KEYCLOAK_REALM: "externo"
  VITE_KEYCLOAK_CLIENT_ID: "maturidadedigital"
  VITE_KEYCLOAK_SSL: "external"
  VITE_KEYCLOAK_PUBLIC_CLIENT: "true"
  VITE_KEYCLOAK_CONFIDENTIAL_PORT: "0"
  
  # Ambiente
  VITE_NODE_ENV: "production"
  VITE_IS_PRODUCTION: "true"
  VITE_IS_DEVELOPMENT: "false"
  VITE_IS_HOMOLOGATION: "false"
