apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: maturidade-digital
  labels:
    app: maturidade-digital-frontend
spec:
  selector:
    app: maturidade-digital-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
